const DB_URL = "mongodb://127.0.0.1:27017/hotelhub";

const API = "http://localhost:3000/api";

const CLOUDINARY_CLOUD_NAME = "dxhzy8hjp";

const CLOUDINARY_API_KEY = "732193517963228";

const CLOUDINARY_API_SECRET = "laHrHWwDnUr_wYP7jdsz8Z7XYyE";

const GOOGLE_API_KEY = "AIzaSyB3ASF_RfqwnLYVMgLe71l45MWYPW65yw4";

const NEXTAUTH_SECRET = "RH53895U3895GFGJTI84TU48T4";

const GOOGLE_CLIENT_ID = "447691197559-ntner8vcfct7iopt7uvc7df1m9jq9p7i.apps.googleusercontent.com";

const GOOGLE_CLIENT_SECRET = "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";

const RAZORPAY_KEY_ID = "rzp_test_579nrQLWfYBIYD";
const RAZORPAY_KEY_SECRET = "BHRRlgPRkOn70429Yz9ffxjD";

const PAYPAL_CLIENT_ID = "AceW9nJb3-RlOq1F9qpl40eCvABcWpTtxCO5rTu47RpdFOoAiQGJSRRKqAPVodkMWTUbVCAyNpBRaZDL";
const PAYPAL_CLIENT_SECRET = "EHGdvjb7JZ2dnhivVEyI_LAJPEWLxOzkxcFkcivqc_HH4nnqUbcYscfqVsOLwxbqiFY7OqHMJkluJoT0";

module.exports = {
  DB_URL,

  API,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  GOOGLE_API_KEY,
  NEXTAUTH_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
  PAYPAL_CLIENT_ID,
  PAYPAL_CLIENT_SECRET,
};
